export const TYPE_SELECT_OPTION_MAP = {
    AD_LANE_DIVIDER_TYPE: [
        { value: 0, label: '未定义' },
        { value: 1, label: '单实线' },
        { value: 2, label: '单虚线' },
        { value: 3, label: '双实线' },
        { value: 4, label: '双虚线' },
        { value: 5, label: '左实右虚' },
        { value: 6, label: '左虚右实' },
        { value: 7, label: '短粗虚线' },
        { value: 8, label: '导流线' },
        { value: 11, label: '车道虚拟线' },
        { value: 12, label: '路边缘虚拟线' },
        { value: 13, label: '防护栏' },
        { value: 14, label: '隧道墙' },
        { value: 15, label: '路缘石' },
        { value: 16, label: '自然边界' },
        { value: 17, label: '施工边界' },
        { value: 18, label: '路口内待行区' }
    ],
    AD_LANE_DIVIDER_DIRECTION: [
        { value: 0, label: '未定义' },
        { value: 1, label: '双向' },
        { value: 2, label: '正向' },
        { value: 3, label: '逆向' }
    ],
    AD_LANE_DIVIDER_REF_LINE: [
        { value: 0, label: '非参考线' },
        { value: 1, label: '参考线' }
    ],
    AD_LANE_DIVIDER_SHARE_LINE: [
        { value: 0, label: '非共用车道线' },
        { value: 1, label: '共用车道线' }
    ],
    AD_LANE_DIVIDER_RD_STATUS: [
        { value: 0, label: '未定义' },
        { value: 1, label: '正常通行' },
        { value: 2, label: '建设中' },
        { value: 3, label: '禁止通行' }
    ],
    AD_LANE_DIVIDER_LANE_TYPE: [
        { value: 1, label: '普通车道' },
        { value: 0, label: '未定义' }
    ],
    AD_REFERENCELINE_TYPE: [
        { value: 0, label: '未定义' },
        { value: 1, label: '非路口内参考线' },
        { value: 2, label: '路口内参考线' }
    ],
    AD_REFERENCELINE_RD_STATUS: [
        { value: 0, label: '未定义' },
        { value: 1, label: '正常通行' },
        { value: 2, label: '建设中' },
        { value: 3, label: '禁止通行' }
    ],
    AD_LANE_TYPE: [
        { value: 0, label: '未定义' },
        { value: 1, label: '普通车道' },
        { value: 2, label: '路口车道' },
        { value: 3, label: '应急车道' },
        { value: 4, label: '非机动车道' },
        { value: 5, label: '机非混合车道' },
        { value: 6, label: '公交车道' },
        { value: 7, label: '人行道' },
        { value: 8, label: 'ETC车道' },
        { value: 9, label: '收费站车道' },
        { value: 10, label: '检查站车道' },
        { value: 11, label: '右侧加速车道' },
        { value: 12, label: '右侧减速车道' },
        { value: 13, label: '匝道' },
        { value: 14, label: '隔离带车道' },
        { value: 15, label: '紧急停车道' },
        { value: 16, label: 'HOV车道' },
        { value: 17, label: '危险用品专用车道' },
        { value: 18, label: '爬坡车道' },
        { value: 19, label: '可变导向车道' },
        { value: 20, label: '海关监管车道' },
        { value: 21, label: '避险车道引道' },
        { value: 22, label: '停车道' },
        { value: 23, label: '潮汐车道' },
        { value: 24, label: '左转待转车道' },
        { value: 25, label: '直行待行车道' },
        { value: 26, label: '掉头车道' },
        { value: 27, label: '超车道' },
        { value: 28, label: '服务区车道' },
        { value: 29, label: '左侧加速车道' },
        { value: 30, label: '左侧减速车道' }
    ],
    AD_LANE_DIRECTION: [
        { value: 0, label: '未定义' },
        { value: 1, label: '双向' },
        { value: 2, label: '正向' },
        { value: 3, label: '逆向' }
    ],
    AD_LANE_RESTRICT: [
        { value: 0, label: '未定义' },
        { value: 1, label: '速度限制' },
        { value: 2, label: '时间限制' }
    ],
    AD_LANE_STATUS: [
        { value: 0, label: '未定义' },
        { value: 1, label: '正常通行' },
        { value: 2, label: '建设中' },
        { value: 2, label: '禁止通行' }
    ],
    AD_LANEATTRPOINT_TYPE: [
        { value: 0, label: '未制作' },
        { value: 11, label: '右侧出口' },
        { value: 12, label: '左侧出口' },
        { value: 15, label: '道路分离点' },
        { value: 16, label: '道路合并点' },
        { value: 17, label: '车道合并点' },
        { value: 20, label: '点云不清晰起始' },
        { value: 40, label: '点云遮挡起始' },
        { value: 50, label: '精度误差起始' },
        { value: 60, label: '道路施工起始' },
        { value: 21, label: '点云不清晰结束' },
        { value: 41, label: '点云遮挡结束' },
        { value: 51, label: '精度误差结束' },
        { value: 61, label: '道路施工结束' }
    ],
    AD_STOPLOCATION_TYPE: [
        { value: 1, label: '停止线' },
        { value: 2, label: '停车让行线' },
        { value: 3, label: '减速让行线' }
    ],
    AD_POLYGON_TYPE: [
        { value: 1, label: '人行横道' },
        { value: 2, label: '禁止停车线' },
        { value: 3, label: '减速带' },
        { value: 4, label: '减速警示震荡线' }
    ],
    AD_TRAFFICSIGN_TYPE: [
        { value: 101, label: '交叉路口' },
        { value: 102, label: '急弯路' },
        { value: 103, label: '反向弯路' },
        { value: 104, label: '连续弯路' },
        { value: 105, label: '陡坡' },
        { value: 106, label: '连续下坡' },
        { value: 107, label: '窄路' },
        { value: 108, label: '窄桥' },
        { value: 109, label: '易滑' },
        { value: 110, label: '双向交通' },
        { value: 111, label: '注意行人' },
        { value: 112, label: '注意儿童' },
        { value: 113, label: '注意牲畜' },
        { value: 114, label: '渡口' },
        { value: 115, label: '注意野生动物' },
        { value: 116, label: '注意信号灯' },
        { value: 117, label: '村庄' },
        { value: 118, label: '注意落石' },
        { value: 119, label: '注意横风' },
        { value: 120, label: '傍山险路' },
        { value: 121, label: '堤坝路' },
        { value: 122, label: '隧道' },
        { value: 123, label: '驼峰桥' },
        { value: 124, label: '路面不平' },
        { value: 125, label: '路面高突' },
        { value: 126, label: '路面低洼' },
        { value: 127, label: '过水路面（漫水桥）' },
        { value: 128, label: '铁路道口' },
        { value: 129, label: '人行横道' },
        { value: 130, label: '注意非机动车' },
        { value: 131, label: '注意残疾人' },
        { value: 132, label: '事故易发路段' },
        { value: 133, label: '慢行' },
        { value: 134, label: '注意障碍物绕行' },
        { value: 135, label: '注意危险' },
        { value: 136, label: '施工' },
        { value: 137, label: '建议速度' },
        { value: 138, label: '注意潮汐车道' },
        { value: 139, label: '避险车道' },
        { value: 140, label: '注意合流' },
        { value: 141, label: '注意分离式道路' },
        { value: 142, label: '注意保持车距' },
        { value: 143, label: '注意前方车辆排队' },
        { value: 144, label: '注意路面结冰、雨（雪）天气' },
        { value: 201, label: '停车让行' },
        { value: 202, label: '减速让行' },
        { value: 203, label: '会车让行' },
        { value: 204, label: '禁止通行' },
        { value: 205, label: '禁止驶入' },
        { value: 206, label: '禁止机动车驶入' },
        { value: 207, label: '禁止向左转弯' },
        { value: 208, label: '禁止向右转弯' },
        { value: 209, label: '禁止直行' },
        { value: 210, label: '禁止向左向右转弯' },
        { value: 211, label: '禁止直行和向左转弯' },
        { value: 212, label: '禁止直行和向右转弯' },
        { value: 213, label: '禁止掉头' },
        { value: 214, label: '禁止超车' },
        { value: 215, label: '解除禁止超车' },
        { value: 216, label: '禁止停车' },
        { value: 217, label: '禁止长时停车' },
        { value: 218, label: '禁止鸣喇叭' },
        { value: 219, label: '限制速度' },
        { value: 220, label: '解除限制速度' },
        { value: 221, label: '停车检查' },
        { value: 222, label: '海关' },
        { value: 223, label: '区域禁止' },
        { value: 224, label: '区域禁止解除' },
        { value: 225, label: '禁止标志' },
        { value: 301, label: '直行' },
        { value: 302, label: '向左转弯' },
        { value: 303, label: '向右转弯' },
        { value: 304, label: '直行和向左转弯' },
        { value: 305, label: '直行和向右行驶' },
        { value: 306, label: '向左和向右行驶' },
        { value: 307, label: '靠左侧道路行驶' },
        { value: 308, label: '靠右侧道路行驶' },
        { value: 309, label: '立体交叉行驶路线' },
        { value: 310, label: '环岛行驶' },
        { value: 311, label: '单行路' },
        { value: 312, label: '步行' },
        { value: 313, label: '鸣喇叭' },
        { value: 314, label: '最低限速' },
        { value: 315, label: '路口优先通行' },
        { value: 316, label: '会车先行' },
        { value: 317, label: '人行横道' },
        { value: 318, label: '车道行驶方向' },
        { value: 319, label: '专用道路和车道' },
        { value: 320, label: '停车位' },
        { value: 321, label: '允许掉头' },
        { value: 400, label: '其他' },
        { value: 500, label: '动态标志牌' }
    ],
    AD_TRAFFICLIGHT_TYPE: [
        { value: 0, label: '其他' },
        { value: 1, label: '普通机动车信号灯' },
        { value: 2, label: '方向指示信号灯' },
        { value: 3, label: '道路与铁路平面交叉道口信号灯' }
    ]
};
