export const OTHER_CONFIG = {
    pointLimit: 5000000,
    viewChangeDelay: 500,
    pollingInterval: 2,
    repairNodeDensity: 0.5,
    adsorptionSensitivity: 0.15,
    outputEditLayer: '["AD_LaneDivider"]',
    pollingLimit: 180,
    drawNodeDensity: 0.5,
    statisticInterval: 1,
    inputEditLayer: '["AD_LaneDivider","AD_StopLocation"]',
    startZ: 6,
    dashedRectangleConstruct: 0.16,
    ZT1: 1000,
    pavementZ: 6,
    overallPollingInterval: 5,
    ZT2: 1000,
    scaleSize: 1,
    finePollingInterval: 1,
    updStatAllChecked: true,
    autoConnectRel: true,
    bufferDiff: 0.01
};
