export const TOOLS_MAP = {
    EDIT: {
        UNDO: true,
        REDO: true,
        SAVE: true,
        EXPORT_SHP: true,
        ZOOM_IN: true,
        ZOOM_OUT: true,
        UNDER_VIEW: true,
        TOP_VIEW: true,
        INTENSITY: true,
        POINT_STRATIFICATION: true,
        SEARCHINFO: true,
        RANGING: true,
        EDIT_LAYER: true,
        POINT: false,
        LINE: false,
        POLYGON: false,
        ADD_GROUND_RECTANGLE: false,
        RESOURCE_LOADER: false,
        ADD_OUTSIDE_RECTANGLE: false,
        ADD_FACADEREC_TANGLE: false,
        ADD_CIRCLE: false,
        ADD_REL: false,
        DEL_REL: false,
        ADJUST_POINT_SIZE: true,
        VIEW_ATTRIBUTE: true,
        READ_COORDINATE: true,
        SEARCH_INFO: true
    },
    CHECK: {}
};
