export const TOOLS_MAP = {
    EDIT: {
        UNDO: true,
        REDO: true,
        SAVE: true,
        // EXPORT_SHP: !NOSHP,
        ZOOM_IN: true,
        ZOOM_OUT: true,
        UNDER_VIEW: true,
        TOP_VIEW: true,
        INTENSITY: true,
        POINT_STRATIFICATION: true,
        SEARCHINFO: true,
        QC_MARKER: true,
        TOP_BREAK_LINE: true,
        EDIT_LAYER: true,
        ADD_REL: false,
        DEL_REL: false,
        ADJUST_POINT_SIZE: true,
        VIEW_ATTRIBUTE: true,
        SEARCH_INFO: false,
        QUALITY_TEST: true,
        POINT_CLOUD: true,
        TOOL_BOX: true,
        DRAW_TOOL_BOX: false,
        RESOURCE_LOADER: true,
        BATCH_TOOL_BOX: false,
        ATTRIBUTE_BRUSH: false,
        POSTURE_ADJUST: false
    },
    CHECK: {}
};
